# Generated by Django 4.1.7 on 2023-02-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0002_threadmodel_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='title',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
